[project]
name = "numpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
]

[dependency-groups]
dev = [
    "numpy",
]

[tool.uv.sources]
numpy = { workspace = true }
